title: HackerCouch
description: CouchSurfing for Hackers
url: http://hackercouch.com

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .editorconfig
  - .gitignore
  - .travis.yml
  - CNAME
  - README.md
  - Gemfile*

collections:
  couches:
    output: true
defaults:
  - scope:
      type: couches
    values:
      layout: couch
