title: HackerCouch
email: me@captnemo.in
description: CouchSurfing for Hackers
url: http://hackercouch.com

markdown: kramdown
collections:
  couches:
    output: true
defaults:
  - scope:
      type: couches
    values:
      layout: couch